version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/moviebooktracker
      - MONGO_URI_LOCAL=mongodb://mongo:27017/moviebooktracker
      - MONGO_URI_CLOUD=mongodb+srv://Achi:Achi%40123@cluster0.suzhbmy.mongodb.net/moviebooktracker?retryWrites=true&w=majority
      - JWT_SECRET=4b7f8e9c2a1d5f0b9c3e6d7a8f2b1c0d
      - NODE_ENV=development
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3002:3002"
    depends_on:
      - backend

volumes:
  mongo-data:
